"""
Guasti Utilities Module
=======================

Utility functions for the Guasti Transform.

Author: Alexandre Guasti
License: MIT
"""

import numpy as np
from math import sqrt, log
from typing import List, Tuple, Dict, Any


def generate_number_table(N_max: int = 100) -> Dict[int, Dict[str, Any]]:
    """
    Generate a comprehensive table of Guasti properties for numbers 2 to N_max.
    
    Parameters
    ----------
    N_max : int
        Maximum number to include.
        
    Returns
    -------
    Dict[int, Dict[str, Any]]
        Dictionary mapping each number to its properties.
    """
    from .guasti_core import (
        tau, sigma, is_prime, angular_signature, 
        has_45_degree, classify_by_signature, multiplicative_entropy
    )
    
    table = {}
    for n in range(2, N_max + 1):
        sqrt_n = int(sqrt(n))
        table[n] = {
            'n': n,
            'is_prime': is_prime(n),
            'is_square': sqrt_n * sqrt_n == n,
            'tau': tau(n),
            'sigma': sigma(n),
            'entropy': multiplicative_entropy(n),
            'signature': angular_signature(n),
            'has_45': has_45_degree(n),
            'classification': classify_by_signature(n)
        }
    return table


def export_to_csv(table: Dict[int, Dict[str, Any]], filename: str) -> None:
    """
    Export number table to CSV file.
    
    Parameters
    ----------
    table : Dict
        Table generated by generate_number_table.
    filename : str
        Output filename.
    """
    import csv
    
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        # Header
        writer.writerow(['n', 'is_prime', 'is_square', 'tau', 'sigma', 
                        'entropy', 'has_45', 'classification', 'signature'])
        # Data
        for n, props in sorted(table.items()):
            writer.writerow([
                n,
                props['is_prime'],
                props['is_square'],
                props['tau'],
                props['sigma'],
                f"{props['entropy']:.3f}",
                props['has_45'],
                props['classification'],
                str(props['signature'])
            ])


def format_signature(sig: set) -> str:
    """Format a signature set as a readable string."""
    return "{" + ", ".join(f"{a:.1f}°" for a in sorted(sig)) + "}"


def print_theorem_summary() -> None:
    """Print a summary of all 9 theorems."""
    theorems = [
        ("T1", "45° Criterion", "n is perfect square ⟺ 45° ∈ Θ(n)"),
        ("T2", "Prime Square Signature", "p² has Θ = {45°, 90°}"),
        ("T3", "Guasti-Pythagoras Identity", "k² + 2ab = (a+b)²"),
        ("T4", "Spectral Inheritance", "Mod 4 class affects angular distribution"),
        ("T5", "Divisor-Angle Correspondence", "τ(n) = |Θ(n)|"),
        ("T6", "Geometric Exclusion", "Primes excluded from grid center"),
        ("T7", "Structural Robustness", "Invariants survive representation changes"),
        ("T8", "Topological Classification", "RIGID/CRYSTALLINE/ELASTIC types"),
        ("T9", "Elastic Deformation", "Homotopic complexity metric"),
    ]
    
    print("=" * 70)
    print("THE 9 GUASTI THEOREMS")
    print("=" * 70)
    for code, name, statement in theorems:
        print(f"\n{code}: {name}")
        print(f"    {statement}")
    print("\n" + "=" * 70)
